baseURL: https://ypiolet.fr
languageCode: en-us
title: ~ypiolet
enableEmoji: true
enableGitInfo: true

# enableRobotsTXT: true
# googleAnalytics: ""

params:
  author: Youenn Piolet
  author-github: https://github.com/uZer
  footer: Copyright test

menu:
  main:
  - name: posts
    url: /posts/
  - name: projects
    url: /projects/
  - name: logs
    url: /logs/
  - name: about
    url: /pages/about/
