baseURL: https://ypiolet.fr
languageCode: en-us
title: ~ypiolet
enableEmoji: true
enableGitInfo: true

# enableRobotsTXT: true
# googleAnalytics: ""

params:
  author: Youenn Piolet
  author-github: https://github.com/uZer
  footer: Copyright test

menu:
  main:
  - identifier: posts
    title: misc articles
    url: /posts/
  - identifier: projects
    title: projects and occupations
    url: /projects/
  - identifier: data
    title: sharing knowledge
    url: /data/
  - identifier: logs
    title: quantified self
    url: /logs/
  - identifier: about
    title: whoami
    url: /pages/about/
